In [3]:
import seaborn as sns
planets= sns.load_dataset('planets')
planets.shape

(1035, 6)

In [4]:
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [12]:
decade= 10 * (planets['year'] // 10)
decade= decade.astype(str) + 's'
decade.name= 'decade'
planets.groupby(['method', decade])['number'].sum().unstack().fillna(0) #'method' 및 'decade'에 대한 그룹화를 수행하고, 'number' 열의 합계를 계산한 후 결과를 재구성하고 누락된 값을 0으로 채움.

decade                         1980s  1990s  2000s  2010s
method
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0